### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by victorgveloso** [TestSmells/TestSmellDetector#6]
When I try to run TestSmellDetector on a UNIX-like system the following error is printed out:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 1
        at testsmell.TestFile.getTagName(TestFile.java:44)
        at Main.main(Main.java:91)
```
This error references the following line of code:
```java
    public String getTagName(){
        return testFilePath.split("\\\\")[4];
    }
```
Which explicitly deals with backslashes (used on windows path). So assuming TestSmellDetector is Windows-only: Is Linux support planned?

**Comment by victorgveloso** [comment]
Actually there is a PR (#5) that fix this problem. I'll try that and post a review whether it works or not.

**Comment by victorgveloso** [comment]
#5 fixed and merged!
